services:

  vpn-proxy:
    image: serjs/go-socks5-proxy
    restart: always
    environment:
      - PROXY_USER=admin
      - PROXY_PASSWORD=parola1109
    ports:
      - "1080:1080"

  baza_de_date:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: proict_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  bot_aplicatie:
    build:
      context: .
      dockerfile: bot/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - DATABASE_URL=postgres://user:password@baza_de_date:5432/proict_db?sslmode=disable
    depends_on:
      - baza_de_date

  dispatcher_aplicatie:
    build:
      context: .
      dockerfile: dispatcher/Dockerfile
    environment:
      - DATABASE_URL=postgres://user:password@baza_de_date:5432/proict_db?sslmode=disable
    ports:
      - "8082:8082"
    depends_on:
      - baza_de_date

  crawler_aplicatie:
    build:
      context: .
      dockerfile: crawler/Dockerfile
    environment:
      - DATABASE_URL=postgres://user:password@baza_de_date:5432/proict_db?sslmode=disable
    depends_on:
      - baza_de_date

volumes:
  postgres_data: